# Managed by NixOS configuration
# Additional substituters for CachyOS kernel binary cache
substituters = https://cache.nixos.org/ https://attic.xuyh0120.win/lantian
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= lantian:EeAUQ+W+6r7EtwnmYjeVwx5kOGEBpjlBfPlzGlTNvHc=
